Fixed for Linux and slowed it down.

diff --git a/speak b/speak
--- a/speak
+++ b/speak
@@ -6,13 +6,10 @@ set -o pipefail
 # A utility to do text-to-speech in the terminal.
 # Credit: Evan Hahn [https://codeberg.org/EvanHahn]
 
-if hash say 2>/dev/null; then
+if hash espeak-ng 2>/dev/null; then
 	pandoc -f commonmark -t plain --wrap=preserve | \
-		say
-elif hash espeak-ng 2>/dev/null; then
-	pandoc -f commonmark -t plain --wrap=preserve | \
-		espeak-ng
+		espeak-ng -s 130
 else
-	>&2 echo "couldn't find any TTS program"
+	>&2 echo "[-] Error: Couldn't find any TTS program. If Linux install espeak-ng."
 	exit 1
 fi
